version: '3'

services:
  fastapi:
    build: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back/images.db:/app/images.db

  react:
    build: ./front
    ports:
      - "5173:5173"
    depends_on:
      - fastapi
